title: Epicycle.Physics (.NET)
url: https://github.com/open-epicycle/Epicycle.Geodesy-cs
summary: "Epicycle .NET physics library."

organization: Epicycle
tags: epicycle lib library physics sensor sensors gps simulation
copyright: Copyright 2015 Epicycle
license_url: http://www.apache.org/licenses/LICENSE-2.0

release_notes: https://github.com/open-epicycle/Epicycle.Physics-cs/blob/ver-$version$/README.md

dotnet_frameworks:
 - net35
 - net40
 - net45

nuget_dependencies:
 - Epicycle.Commons-cs.0.1.6.0
 - Epicycle.Math-cs.0.1.3.0
 - Epicycle.Geodesy-cs.0.1.0.0

description: |
   Epicycle .NET physics library.
   
   * Details & release notes: https://github.com/open-epicycle/Epicycle.Physics-cs/blob/ver-$version$/README.md
   * Sources: https://github.com/open-epicycle/Epicycle.Physics-cs/tree/ver-$version$
   * Git repository: https://github.com/open-epicycle/Epicycle.Physics-cs